version: '2'
services:
  api:
    container_name: api
    build: .
    ports:
      - '80:80'
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
